/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SoulRouteImport } from "./routes/soul"
import { Route as SkillsRouteImport } from "./routes/skills"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as KanbanRouteImport } from "./routes/kanban"
import { Route as FilesRouteImport } from "./routes/files"
import { Route as CredentialsRouteImport } from "./routes/credentials"
import { Route as CalendarRouteImport } from "./routes/calendar"
import { Route as IndexRouteImport } from "./routes/index"

const SoulRoute = SoulRouteImport.update({
  id: "/soul",
  path: "/soul",
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: "/kanban",
  path: "/kanban",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: "/credentials",
  path: "/credentials",
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/calendar": typeof CalendarRoute
  "/credentials": typeof CredentialsRoute
  "/files": typeof FilesRoute
  "/kanban": typeof KanbanRoute
  "/settings": typeof SettingsRoute
  "/skills": typeof SkillsRoute
  "/soul": typeof SoulRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/calendar": typeof CalendarRoute
  "/credentials": typeof CredentialsRoute
  "/files": typeof FilesRoute
  "/kanban": typeof KanbanRoute
  "/settings": typeof SettingsRoute
  "/skills": typeof SkillsRoute
  "/soul": typeof SoulRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/calendar": typeof CalendarRoute
  "/credentials": typeof CredentialsRoute
  "/files": typeof FilesRoute
  "/kanban": typeof KanbanRoute
  "/settings": typeof SettingsRoute
  "/skills": typeof SkillsRoute
  "/soul": typeof SoulRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/calendar"
    | "/credentials"
    | "/files"
    | "/kanban"
    | "/settings"
    | "/skills"
    | "/soul"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/calendar"
    | "/credentials"
    | "/files"
    | "/kanban"
    | "/settings"
    | "/skills"
    | "/soul"
  id:
    | "__root__"
    | "/"
    | "/calendar"
    | "/credentials"
    | "/files"
    | "/kanban"
    | "/settings"
    | "/skills"
    | "/soul"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CredentialsRoute: typeof CredentialsRoute
  FilesRoute: typeof FilesRoute
  KanbanRoute: typeof KanbanRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SoulRoute: typeof SoulRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/soul": {
      id: "/soul"
      path: "/soul"
      fullPath: "/soul"
      preLoaderRoute: typeof SoulRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/skills": {
      id: "/skills"
      path: "/skills"
      fullPath: "/skills"
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/kanban": {
      id: "/kanban"
      path: "/kanban"
      fullPath: "/kanban"
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files": {
      id: "/files"
      path: "/files"
      fullPath: "/files"
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/credentials": {
      id: "/credentials"
      path: "/credentials"
      fullPath: "/credentials"
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/calendar": {
      id: "/calendar"
      path: "/calendar"
      fullPath: "/calendar"
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CredentialsRoute: CredentialsRoute,
  FilesRoute: FilesRoute,
  KanbanRoute: KanbanRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SoulRoute: SoulRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
